services:
  details:
    build:
      context: .
      network: host
    image: trace-fusion-bookinfo-http2:latest
    container_name: bookinfo-http2-details
    environment:
      SERVICE_ROLE: details
      BOOK_COUNT: 100
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      ALL_PROXY: ""
      NO_PROXY: "*"
      http_proxy: ""
      https_proxy: ""
      all_proxy: ""
      no_proxy: "*"
    ports:
      - "9451:9080"

  ratings:
    build:
      context: .
      network: host
    image: trace-fusion-bookinfo-http2:latest
    container_name: bookinfo-http2-ratings
    environment:
      SERVICE_ROLE: ratings
      BOOK_COUNT: 100
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      ALL_PROXY: ""
      NO_PROXY: "*"
      http_proxy: ""
      https_proxy: ""
      all_proxy: ""
      no_proxy: "*"
    ports:
      - "9452:9080"

  reviews:
    build:
      context: .
      network: host
    image: trace-fusion-bookinfo-http2:latest
    container_name: bookinfo-http2-reviews
    environment:
      SERVICE_ROLE: reviews
      RATINGS_HOSTNAME: ratings
      RATINGS_SERVICE_PORT: 9080
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      ALL_PROXY: ""
      NO_PROXY: "*"
      http_proxy: ""
      https_proxy: ""
      all_proxy: ""
      no_proxy: "*"
    depends_on:
      - ratings
    ports:
      - "9453:9080"

  productpage:
    build:
      context: .
      network: host
    image: trace-fusion-bookinfo-http2:latest
    container_name: bookinfo-http2-productpage
    environment:
      SERVICE_ROLE: productpage
      BOOK_COUNT: 100
      DETAILS_HOSTNAME: details
      DETAILS_SERVICE_PORT: 9080
      REVIEWS_HOSTNAME: reviews
      REVIEWS_SERVICE_PORT: 9080
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      ALL_PROXY: ""
      NO_PROXY: "*"
      http_proxy: ""
      https_proxy: ""
      all_proxy: ""
      no_proxy: "*"
    depends_on:
      - details
      - reviews
    ports:
      - "9450:9080"
