[workspace]
resolver = "2"
members = [
    "tls-uprobe",
    "tls-uprobe-common",
    "tls-uprobe-ebpf",
]
default-members = ["tls-uprobe", "tls-uprobe-common"]

[workspace.package]
license = "MIT OR Apache-2.0"
edition = "2024"

[workspace.dependencies]
aya = { git = "https://github.com/aya-rs/aya", default-features = false }
aya-build = { git = "https://github.com/aya-rs/aya", default-features = false }
aya-ebpf = { git = "https://github.com/aya-rs/aya", default-features = false }

anyhow = { version = "1", default-features = false }
cargo_metadata = { version = "0.23.0", default-features = false }
chrono = { version = "0.4" }
clap = { version = "4.5.20", default-features = false, features = ["std", "help", "usage"] }
env_logger = { version = "0.11.5", default-features = false }
libc = { version = "0.2.159", default-features = false }
log = { version = "0.4.22", default-features = false }
tokio = { version = "1.40.0", default-features = false }
which = { version = "6.0.0", default-features = false }

[profile.release.package.tls-uprobe-ebpf]
debug = 2
codegen-units = 1
