[package]
name = "cgroup-ebpf"
version = "0.1.0"
edition.workspace = true

[dependencies]
cgroup-common = { path = "../cgroup-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }
network-types = "0.1.0"

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "cgroup"
path = "src/main.rs"
